name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update tryhackme badge image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "0xR1Y4Z" # Put your TryHackMe username here
          use_static_image: "false" # Forces the action to use the live API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
